### ISSUE TITLE
Whole presentation overview and print mode

### ISSUE THREAD

**Issue by kirjs** [kirjs/angular-presentation#18]

**Comment by prestonvanloon** [comment]
Could you provide some details to this issue?

**Comment by kirjs** [comment]
Basically I need a button which will show previews of all slides on the screen, and also make it printable to a PDF. 
This task is pretty simple, but is also pretty low priority. 

![image](https://cloud.githubusercontent.com/assets/2545357/25362782/1f6efcee-2924-11e7-9be9-f39fd7df4aa0.png)

**Comment by kirjs** [comment]
Fixed thanks to @foozebox
