### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by aziz512** [kirjs/angular-presentation#6]
This issue addresses migrating content from Google Slides to HTML slides
[link to the slides](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/)

[Most of the slides](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g165e56e4e2_0_376):
- [ ] file names under code (for ex. slides 20-22)
- [ ] text is white or gray
- [ ] highlight code and put a box around it
- [ ] have fixed (always in the same place) current section (gray) & title (white)

[slide 1-2](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g1b20e4e474_0_55):
- [x] background image - scale&position 
No background for now

[Slides 3-75](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g165e56e4e2_0_123):
- [x] gray background

[Slide 4](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g165e56e4e2_0_128):
- [x] grid boxes of different color

[Slide 5](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g165e56e4e2_0_146):
- [x] TS graph

[Slides 5, 74](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g165e56e4e2_0_146):
- [ ] Notes on the bottom

[Slides 7, 9](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g1aa0f8d99c_0_4):
- [ ] huge titles
- [ ] highlighted words

[Slide 11](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g1a4e747a5b_0_0):
- [x] custom code highlight (red)	

[Slides 10-15](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g1a4e747a5b_0_0):
- [ ] yellow tooltips on the code
- [x] very large code

['Content' slides (i.e. 8 or 19)](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g1b20e4e474_0_6) (Can be generated?):
- [x] Highlight current section with yellow & bigger font

[Slides 20, 21, 32](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g165e56e4e2_0_191):
- [x] arrows pointing to code

[Slides 45, 47, 64](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g165e56e4e2_0_549):
- [x] position multiple boxes of code

[Slides 46, 50, 52](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g165e56e4e2_0_570):
- [ ] Mixed code boxes & arrows & colored boxes 

Slide 67, 68:
- [ ] display output

[Slide 58, 59, 60, 62, 63](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g177fc3b00e_0_42):
- [ ] add image
- [ ] add colored filter on image

[Slides 3, 36, 60](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g165e56e4e2_0_123):
- [ ] highlighted words in different colors (i.e. slide 3)

[Slides 17, 18, 23, 33, 41, 48, 54, 65](https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g13c954a7ff_3_31):
- [ ] Directions title in gray and bigger font

**Comment by kirjs** [comment]
Closing as we're not reimplementing slides anymore
